/*
 * SixtrisView.java
 */

package sixtris;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class SixtrisView extends FrameView {

	public sixtris.Plateau getPlateau(){
		return plateau1;
	}

	public sixtris.Preview getPreview(){
		return preview1;
	}

	public void init(){
		SixtrisApp.getApplication().game.addActionListener(new ActionListener(){
			public void actionPerformed( ActionEvent e ){
				Game game = (Game)e.getSource();
				jLevel.setText(String.valueOf(game.level));
				jLines.setText(String.valueOf(game.getLines()));
				jScore.setText(String.valueOf(game.getScore()));
			}
		});
		plateau1.setTheme( SixtrisApp.getApplication().theme );
		plateau1.setConfig( SixtrisApp.getApplication().config );
		
		preview1.setTheme( SixtrisApp.getApplication().theme );
	}

	public SixtrisView(SingleFrameApplication app) {
		super(app);

		initComponents();
	}

	@Action
	public void newGame(){
		SixtrisApp.getApplication().game.start();
	}
	
	@Action
	public void showAboutBox() {
		if (aboutBox == null) {
			JFrame mainFrame = SixtrisApp.getApplication().getMainFrame();
			aboutBox = new SixtrisAboutBox(mainFrame);
			aboutBox.setLocationRelativeTo(mainFrame);
		}
		SixtrisApp.getApplication().show(aboutBox);
	}

	@Action
	public void showConfigBox() {
		if (configBox == null){
			JFrame mainFrame = SixtrisApp.getApplication().getMainFrame();
			configBox = new SixtrisConfigBox(mainFrame);
			configBox.setLocationRelativeTo(mainFrame);
		}
		SixtrisApp.getApplication().show(configBox);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    mainPanel = new javax.swing.JPanel();
    plateau1 = new sixtris.Plateau();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
    jPanel1 = new javax.swing.JPanel();
    preview1 = new sixtris.Preview();
    jLabel2 = new javax.swing.JLabel();
    jLevel = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLines = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jScore = new javax.swing.JLabel();
    menuBar = new javax.swing.JMenuBar();
    javax.swing.JMenu fileMenu = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
    editMenu = new javax.swing.JMenu();
    configMenuItem = new javax.swing.JMenuItem();
    javax.swing.JMenu helpMenu = new javax.swing.JMenu();
    javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

    mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    mainPanel.setName("mainPanel"); // NOI18N
    mainPanel.setOpaque(false);

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sixtris.SixtrisApp.class).getContext().getResourceMap(SixtrisView.class);
    plateau1.setBackground(resourceMap.getColor("plateau1.background")); // NOI18N
    plateau1.setMaximumSize(null);
    plateau1.setName("plateau1"); // NOI18N
    plateau1.setPreferredSize(new java.awt.Dimension(267, 500));
    plateau1.addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentResized(java.awt.event.ComponentEvent evt) {
        plateau1ComponentResized(evt);
      }
    });

    javax.swing.GroupLayout plateau1Layout = new javax.swing.GroupLayout(plateau1);
    plateau1.setLayout(plateau1Layout);
    plateau1Layout.setHorizontalGroup(
      plateau1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 267, Short.MAX_VALUE)
    );
    plateau1Layout.setVerticalGroup(
      plateau1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 500, Short.MAX_VALUE)
    );

    filler1.setName("filler1"); // NOI18N

    jPanel1.setName("jPanel1"); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 120, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 59, Short.MAX_VALUE)
    );

    preview1.setName("preview1"); // NOI18N

    javax.swing.GroupLayout preview1Layout = new javax.swing.GroupLayout(preview1);
    preview1.setLayout(preview1Layout);
    preview1Layout.setHorizontalGroup(
      preview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    preview1Layout.setVerticalGroup(
      preview1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
    jLabel2.setName("jLabel2"); // NOI18N

    jLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLevel.setText(resourceMap.getString("jLevel.text")); // NOI18N
    jLevel.setName("jLevel"); // NOI18N

    jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
    jLabel1.setMaximumSize(new java.awt.Dimension(42, 15));
    jLabel1.setMinimumSize(new java.awt.Dimension(42, 15));
    jLabel1.setName("jLabel1"); // NOI18N
    jLabel1.setPreferredSize(new java.awt.Dimension(42, 15));

    jLines.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLines.setText(resourceMap.getString("jLines.text")); // NOI18N
    jLines.setName("jLines"); // NOI18N

    jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
    jLabel3.setMaximumSize(new java.awt.Dimension(42, 15));
    jLabel3.setMinimumSize(new java.awt.Dimension(42, 15));
    jLabel3.setName("jLabel3"); // NOI18N
    jLabel3.setPreferredSize(new java.awt.Dimension(42, 15));

    jScore.setFont(resourceMap.getFont("jScore.font")); // NOI18N
    jScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jScore.setText(resourceMap.getString("jScore.text")); // NOI18N
    jScore.setName("jScore"); // NOI18N

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
      mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(plateau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(mainPanelLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel2)
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jScore, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLines, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
          .addGroup(mainPanelLayout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(preview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(330, Short.MAX_VALUE))
    );
    mainPanelLayout.setVerticalGroup(
      mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(plateau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(mainPanelLayout.createSequentialGroup()
            .addComponent(preview1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(jLevel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLines))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScore))
            .addGap(9, 9, 9)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(267, 267, 267)
            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(266, Short.MAX_VALUE))
    );

    menuBar.setName("menuBar"); // NOI18N

    fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
    fileMenu.setName("fileMenu"); // NOI18N

    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sixtris.SixtrisApp.class).getContext().getActionMap(SixtrisView.class, this);
    jMenuItem1.setAction(actionMap.get("newGame")); // NOI18N
    jMenuItem1.setText(resourceMap.getString("NewDoneMenuItem.text")); // NOI18N
    jMenuItem1.setToolTipText(resourceMap.getString("NewDoneMenuItem.toolTipText")); // NOI18N
    jMenuItem1.setName("NewDoneMenuItem"); // NOI18N
    fileMenu.add(jMenuItem1);

    exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
    exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
    exitMenuItem.setName("exitMenuItem"); // NOI18N
    fileMenu.add(exitMenuItem);

    menuBar.add(fileMenu);

    editMenu.setText(resourceMap.getString("show.text")); // NOI18N
    editMenu.setName("show"); // NOI18N

    configMenuItem.setAction(actionMap.get("showConfigBox")); // NOI18N
    configMenuItem.setText(resourceMap.getString("configMenuItem.text")); // NOI18N
    configMenuItem.setName("configMenuItem"); // NOI18N
    editMenu.add(configMenuItem);

    menuBar.add(editMenu);

    helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
    helpMenu.setName("helpMenu"); // NOI18N

    aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
    aboutMenuItem.setName("aboutMenuItem"); // NOI18N
    helpMenu.add(aboutMenuItem);

    menuBar.add(helpMenu);

    setComponent(mainPanel);
    setMenuBar(menuBar);
  }// </editor-fold>//GEN-END:initComponents

		private void plateau1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_plateau1ComponentResized
			getFrame().setSize(plateau1.getWidth() + preview1.getWidth() + 42, plateau1.getHeight() + 78);
		}//GEN-LAST:event_plateau1ComponentResized

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem configMenuItem;
  private javax.swing.JMenu editMenu;
  private javax.swing.Box.Filler filler1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLevel;
  private javax.swing.JLabel jLines;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel jScore;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JMenuBar menuBar;
  private sixtris.Plateau plateau1;
  private sixtris.Preview preview1;
  // End of variables declaration//GEN-END:variables

	private JDialog aboutBox;
	private JDialog configBox;
}
